### ISSUE TITLE
SyntaxError: Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by rasyidrafi** [ezefranca/youtube-metadata-from-url#2]
I had a problem, pls help,
I dont know what is the problem, but i think 
pls add handler for error, so the programs doesnt stop

`undefined:1
Not Found
^
SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/f85c6ec8-b431-4bbd-a699-6e85062dc2df/node_modules/.registry.npmjs.org/youtube-metadata-from-url/1.0.3/node_modules/youtube-metadata-from-url/index.js:19:37)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)`

![Screenshot (36)](https://user-images.githubusercontent.com/69502214/107641292-06d62300-6ca6-11eb-98f5-b0a98fbc3390.png)

**Comment by ExpErgio** [comment]
I have the same problem, using this link: https://www.youtube.com/user/warnerbrosespana

**Comment by rickvian** [comment]
juding how the index.js works, it only works for video URL, you cannot use channel link

> I have the same problem, using this link: https://www.youtube.com/user/warnerbrosespana
